<?php

namespace Database\Seeders;

use App\Models\Kelurahan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KelurahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Kelurahan::insert([
            [
                'nama_kelurahan' => 'Arjosari',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Borang',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Gayuhan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Gegeran',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Gembong',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Gunungsari',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Jatimalang',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Jetis Kidul',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Karanggede',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Karangrejo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Kedungbendo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Mangunharjo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Mlati',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Pagutan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sedayu',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Temon',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Tremas',
                'kabupaten_id' => 1,
                'kecamatan_id' => 1,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Bandar',
                'kabupaten_id' => 1,
                'kecamatan_id' => 2,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Bangunsari',
                'kabupaten_id' => 1,
                'kecamatan_id' => 2,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Jeruk',
                'kabupaten_id' => 1,
                'kecamatan_id' => 2,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Kledung',
                'kabupaten_id' => 1,
                'kecamatan_id' => 2,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Ngunut',
                'kabupaten_id' => 1,
                'kecamatan_id' => 2,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Petungsinarang',
                'kabupaten_id' => 1,
                'kecamatan_id' => 2,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Tumpuk',
                'kabupaten_id' => 1,
                'kecamatan_id' => 2,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Watupatok',
                'kabupaten_id' => 1,
                'kecamatan_id' => 2,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Belah',
                'kabupaten_id' => 1,
                'kecamatan_id' => 3,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Cemeng',
                'kabupaten_id' => 1,
                'kecamatan_id' => 3,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Donorojo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 3,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Gedompol',
                'kabupaten_id' => 1,
                'kecamatan_id' => 3,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Gendaran',
                'kabupaten_id' => 1,
                'kecamatan_id' => 3,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Kalak',
                'kabupaten_id' => 1,
                'kecamatan_id' => 3,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Klepu',
                'kabupaten_id' => 1,
                'kecamatan_id' => 3,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sawahan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 3,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sekar',
                'kabupaten_id' => 1,
                'kecamatan_id' => 3,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sendang',
                'kabupaten_id' => 1,
                'kecamatan_id' => 3,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sukodono',
                'kabupaten_id' => 1,
                'kecamatan_id' => 3,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Widoro',
                'kabupaten_id' => 1,
                'kecamatan_id' => 3,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Banjarjo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Gawang',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Gembuk',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Kalipelus',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Karanganyar',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Karangnongko',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Katipugal',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Kebonagung',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Ketepung',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Ketro',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Klesem',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Mantren',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Plumbungan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Punjung',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Purwoasri',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sanggrahan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sidomulyo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Wonogondo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Worawari',
                'kabupaten_id' => 1,
                'kecamatan_id' => 4,
                'status' => 'Desa',
            ],

            // Kecamatan Nawangan
            [
                'nama_kelurahan' => 'Gondang',
                'kabupaten_id' => 1,
                'kecamatan_id' => 5,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Jetis Lor',
                'kabupaten_id' => 1,
                'kecamatan_id' => 5,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Mujing',
                'kabupaten_id' => 1,
                'kecamatan_id' => 5,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Nawangan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 5,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Ngromo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 5,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Pakis Baru',
                'kabupaten_id' => 1,
                'kecamatan_id' => 5,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Penggung',
                'kabupaten_id' => 1,
                'kecamatan_id' => 5,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sempu',
                'kabupaten_id' => 1,
                'kecamatan_id' => 5,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Tokawi',
                'kabupaten_id' => 1,
                'kecamatan_id' => 5,
                'status' => 'Desa',
            ],
            //Kecamatan Ngadirojo
            [
                'nama_kelurahan' => 'Bodag',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Bogoharjo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Cangkring',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Cokrokembang',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Hadiluwih',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Hadiwarno',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Ngadirojo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Nogosari',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Pagerejo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sidomulyo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Tanjung Lor',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Tanjungpuro',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Wiyoro',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Wonoasri',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Wonodadi Kulon',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Wonodadi Wetan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Wonokarto',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Wonosobo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 6,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Arjowinangun',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Bangunsari',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Banjarsari',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Bolosingo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Kayen',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Kembang',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Menadi',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Mentoro',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Nanggungan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Ponggok',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Purworejo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sambong',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sedeng',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Semanten',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sirnoboyo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sukoharjo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sumberharjo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Tambakrejo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Tanjungsari',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Widoro',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Baleharjo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Kelurahan',
            ],
            [
                'nama_kelurahan' => 'Pacitan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Kelurahan',
            ],
            [
                'nama_kelurahan' => 'Ploso',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Kelurahan',
            ],
            [
                'nama_kelurahan' => 'Pucangsewu',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Kelurahan',
            ],
            [
                'nama_kelurahan' => 'Sidoharjo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 7,
                'status' => 'Kelurahan',
            ],
            [
                'nama_kelurahan' => 'Candi',
                'kabupaten_id' => 1,
                'kecamatan_id' => 8,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Dadapan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 8,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Dersono',
                'kabupaten_id' => 1,
                'kecamatan_id' => 8,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Glinggangan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 8,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Jlubang',
                'kabupaten_id' => 1,
                'kecamatan_id' => 8,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Ngadirejan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 8,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Pelem',
                'kabupaten_id' => 1,
                'kecamatan_id' => 8,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Poko',
                'kabupaten_id' => 1,
                'kecamatan_id' => 8,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Pringkuku',
                'kabupaten_id' => 1,
                'kecamatan_id' => 8,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sobo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 8,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sugihwaras',
                'kabupaten_id' => 1,
                'kecamatan_id' => 8,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Tamanasri',
                'kabupaten_id' => 1,
                'kecamatan_id' => 8,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Watukarung',
                'kabupaten_id' => 1,
                'kecamatan_id' => 8,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Bomo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 9,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Gondosari',
                'kabupaten_id' => 1,
                'kecamatan_id' => 9,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Kebonsari',
                'kabupaten_id' => 1,
                'kecamatan_id' => 9,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Kendal',
                'kabupaten_id' => 1,
                'kecamatan_id' => 9,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Mantren',
                'kabupaten_id' => 1,
                'kecamatan_id' => 9,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Mendolo Kidul',
                'kabupaten_id' => 1,
                'kecamatan_id' => 9,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Mendolo Lor',
                'kabupaten_id' => 1,
                'kecamatan_id' => 9,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Piton',
                'kabupaten_id' => 1,
                'kecamatan_id' => 9,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Ploso',
                'kabupaten_id' => 1,
                'kecamatan_id' => 9,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Punung',
                'kabupaten_id' => 1,
                'kecamatan_id' => 9,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sooka',
                'kabupaten_id' => 1,
                'kecamatan_id' => 9,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Tinatar',
                'kabupaten_id' => 1,
                'kecamatan_id' => 9,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Wareng',
                'kabupaten_id' => 1,
                'kecamatan_id' => 9,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Gunungrejo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 10,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Karangmulyo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 10,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Ketanggung',
                'kabupaten_id' => 1,
                'kecamatan_id' => 10,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Klepu',
                'kabupaten_id' => 1,
                'kecamatan_id' => 10,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Pager Kidul',
                'kabupaten_id' => 1,
                'kecamatan_id' => 10,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Pager Lor',
                'kabupaten_id' => 1,
                'kecamatan_id' => 10,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sembowo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 10,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sudimoro',
                'kabupaten_id' => 1,
                'kecamatan_id' => 10,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sukorejo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 10,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Sumberejo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 10,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Gedangan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 11,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Gemaharjo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 11,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Kasihan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 11,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Kebondalem',
                'kabupaten_id' => 1,
                'kecamatan_id' => 11,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Kemuning',
                'kabupaten_id' => 1,
                'kecamatan_id' => 11,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Ngreco',
                'kabupaten_id' => 1,
                'kecamatan_id' => 11,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Ploso',
                'kabupaten_id' => 1,
                'kecamatan_id' => 11,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Pucangombo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 11,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Tahunan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 11,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Tahunan Baru',
                'kabupaten_id' => 1,
                'kecamatan_id' => 11,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Tegalombo',
                'kabupaten_id' => 1,
                'kecamatan_id' => 11,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Bubakan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Bungur',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Gasang',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Jatigunung',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Jetak',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Kalikuning',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Ketro',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Kluwih',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Losari',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Ngile',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Nglaran',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Ngumbul',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Padi',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Tulakan',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Wonoanti',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],
            [
                'nama_kelurahan' => 'Wonosidi',
                'kabupaten_id' => 1,
                'kecamatan_id' => 12,
                'status' => 'Desa',
            ],

        ],);
    }
}
